---
- name: CLI packages
  tags: cli,dependencies
  block:
  - name: Ubuntu
    become: true
    when: is_ubuntu
    block:
      - name: Ubuntu | Upgrade the current system
        ansible.builtin.apt:
          update_cache: true
          upgrade: true

      - name: Ubuntu | Add git-core PPA repository for the latest git
        ansible.builtin.apt_repository:
          repo: ppa:git-core/ppa
          state: present

      - name: Ubuntu | Update cache
        ansible.builtin.apt:
          update_cache: true

      - name: Ubuntu | Install packages
        ansible.builtin.apt:
          state: present
          pkg:
            - git
            - unzip
            - make
            - gcc
            - python3-venv
            - wl-clipboard
            - dbus-bin
            - libglib2.0-bin
            - ffmpeg
            - 7zip
            - poppler-utils
            - imagemagick

  - name: Fedora Silverblue
    when: is_fedora_silverblue
    block:
      - name: Fedora Silverblue | Enable pgdev:ghostty copr repository
        become: true
        ansible.builtin.copy:
          dest: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:pgdev:ghostty.repo
          content: |
            [copr:copr.fedorainfracloud.org:pgdev:ghostty]
            name=Copr repo for Ghostty owned by pgdev
            baseurl=https://download.copr.fedorainfracloud.org/results/pgdev/ghostty/fedora-$releasever-$basearch/
            type=rpm-md
            skip_if_unavailable=True
            gpgcheck=1
            gpgkey=https://download.copr.fedorainfracloud.org/results/pgdev/ghostty/pubkey.gpg
            repo_gpgcheck=0
            enabled=1
            enabled_metadata=1

      - name: Fedora Silverblue | Install rpm-ostree packages
        community.general.rpm_ostree_pkg:
          state: present
          name:
            - git
            - gcc
            - glib2-devel
            - tmux
            - wl-clipboard
            - p7zip
            - p7zip-plugins
            - ghostty

      - name: Fedora Silverblue | Add flathub repository
        community.general.flatpak_remote:
          name: flathub
          state: present
          flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
          method: system

      - name: Fedora Silverblue | Install flatpak packages
        community.general.flatpak:
          method: system
          state: present
          name:
            - com.visualstudio.code

      - name: VS Code extensions
        block:
          - name: VS Code extensions | Set common facts
            ansible.builtin.set_fact:
              extensions_file: "{{ playbook_dir | dirname }}/vscode/extensions.json"

          - name: VS Code extensions | Load extensions.json
            ansible.builtin.set_fact:
              extensions: "{{ lookup('file', extensions_file) | from_json }}"

          - name: VS Code extensions | Install
            command: "flatpak run com.visualstudio.code --install-extension {{ item }}"
            loop: "{{ extensions.extensions }}"
            register: extension_install_results
            ignore_errors: true  # Continue if one extension fails
            changed_when: "'already installed' not in extension_install_results.stderr"

  - name: Fedora
    become: true
    when: is_fedora
    block:
      - name: Fedora | Enable pgdev:ghostty copr repository
        ansible.builtin.copy:
          dest: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:pgdev:ghostty.repo
          content: |
            [copr:copr.fedorainfracloud.org:pgdev:ghostty]
            name=Copr repo for Ghostty owned by pgdev
            baseurl=https://download.copr.fedorainfracloud.org/results/pgdev/ghostty/fedora-$releasever-$basearch/
            type=rpm-md
            skip_if_unavailable=True
            gpgcheck=1
            gpgkey=https://download.copr.fedorainfracloud.org/results/pgdev/ghostty/pubkey.gpg
            repo_gpgcheck=0
            enabled=1
            enabled_metadata=1

      - name: Fedora | Install packages
        ansible.builtin.dnf:
          state: present
          name:
            - git
            - gcc
            - glib2-devel
            - tmux
            - wl-clipboard
            - p7zip
            - p7zip-plugins
            - ghostty
