- name: Configure
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - { src: "bashrc", dest: "{{ ansible_env.HOME }}/.bashrc" }
    - { src: "bashrc.d", dest: "{{ ansible_env.HOME }}/.bashrc.d" }
