"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
$username\
$hostname\
$directory\
$git_branch\
\n$character\
"""
palette = "kanagawa-wave"

[palettes.kanagawa-wave]
background  = "#1F1F28"
foreground  = "#DCD7BA"
black       = "#090618"
red         = "#C34043"
green       = "#76946A"
yellow      = "#C0A36E"
blue        = "#7E9CD8"
magenta     = "#957FB8"
cyan        = "#6A9589"
white       = "#C8C093"
orange      = "#FFA066"

[palettes.kanagawa-lotus]
background  = "#F2ECBC"
foreground  = "#545464"
black       = "#1F1F28"
red         = "#C84053"
green       = "#6F894E"
yellow      = "#77713F"
blue        = "#4D699B"
magenta     = "#B35B79"
cyan        = "#597B75"
white       = "#545464"
orange      = "#FFA066"

[palettes.kanagawa-dragon]
background  = "#181616"
foreground  = "#C5C9C5"
black       = "#0D0C0C"
red         = "#C4746E"
green       = "#8A9A7B"
yellow      = "#C4B28A"
blue        = "#8BA4B0"
magenta     = "#A292A3"
cyan        = "#8EA4A2"
white       = "#C8C093"
orange      = "#B6927B"

[palettes.everforest]
background  = "#2D353B"
foreground  = "#D3C6AA"
black       = "#4B565C"
red         = "#E67E80"
green       = "#A7C080"
yellow      = "#DBBC7F"
blue        = "#7FBBB3"
magenta     = "#D699B6"
cyan        = "#83C092"
white       = "#D3C6AA"
orange      = "#E69875"

[palettes.rose-pine-dawn]
background  = "#FAF4ED"
foreground  = "#575279"
black       = "#F2E9E1"
red         = "#B4637A"
green       = "#286983"
yellow      = "#EA9D34"
blue        = "#56949F"
magenta     = "#907AA9"
cyan        = "#D7827E"
white       = "#575279"
orange      = "#D1805C"

[username]
style_user = 'green'
style_root = 'red'
format = '[$user]($style)'
show_always = true

[hostname]
format = ' at [$ssh_symbol](blue)[$hostname](blue)'
ssh_only = false
disabled = false

[directory]
format = ' in [$path](cyan)'
disabled = false

[git_branch]
symbol = ''
format = ' on [$symbol$branch(:$remote_branch)]($style)'
style = 'magenta'
disabled = false

[character]
success_symbol = '[❯](green)'
