# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook

- name: System setup for Ubuntu (system-level tasks)
  hosts: localhost
  become: true
  tasks:
    - name: Ensure target system is Debian or Ubuntu
      ansible.builtin.assert:
        that:
          - ansible_distribution in ['Debian', 'Ubuntu']
        fail_msg: "This playbook requires Debian or Ubuntu on the target server"

    - name: Add git-core PPA repository for the latest git
      ansible.builtin.apt_repository:
        repo: ppa:git-core/ppa
        state: present

    - name: Upgrade the current system
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Install dependencies for neovim configuration
      ansible.builtin.apt:
        state: latest
        pkg:
          - git
          - unzip
          - make
          - gcc
          - python3-venv
          - fzf
          - ripgrep
          - wl-clipboard
          - dbus-bin

    - name: Install dependencies for yazi
      ansible.builtin.apt:
        state: latest
        pkg:
          - ffmpeg
          - 7zip
          - jq
          - fzf
          - ripgrep
          - poppler-utils
          - imagemagick

    - name: Install additional cli tools
      ansible.builtin.apt:
        state: latest
        pkg:
          - libglib2.0-bin
          - jq
          - yq

    - name: Install bat
      ansible.builtin.import_tasks: tasks/bat.yaml
      tags: bat

    - name: Install eza
      ansible.builtin.import_tasks: tasks/eza.yaml
      tags: eza

    - name: Install fd
      ansible.builtin.import_tasks: tasks/fd.yaml
      tags: fd

    - name: Install yazi
      ansible.builtin.import_tasks: tasks/yazi.yaml
      tags: yazi

    - name: Install fnm and node LTS
      ansible.builtin.import_tasks: tasks/fnm.yaml
      tags: fnm

    - name: Install neovim
      ansible.builtin.import_tasks: tasks/nvim.yaml
      tags: neovim

    - name: Install starship
      ansible.builtin.import_tasks: tasks/starship.yaml
      tags: starship

    - name: Add binary from /opt to PATH
      ansible.builtin.copy:
        dest: /etc/profile.d/extra-binaries-opt.sh
        mode: "0644"
        content: |
          export PATH="/opt/bat:$PATH"
          export PATH="/opt/eza:$PATH"
          export PATH="/opt/fd:$PATH"
          export PATH="/opt/yazi:$PATH"
          export PATH="/opt/nvim-linux-x86_64/bin:$PATH"
          export PATH="/opt/starship:$PATH"

    - name: Create fix for wayland copy/paste
      ansible.builtin.import_tasks: tasks/wsl-fix-wayland.yaml
      tags: fix-wayland

- name: User-specific configuration
  hosts: localhost
  tasks:
    - name: Set common facts
      ansible.builtin.set_fact:
        repository_dir: "{{ playbook_dir | dirname }}"
        config_dir: "{{ ansible_env.HOME }}/.config"

    - name: Ensure .config directory exists in the user's home
      ansible.builtin.file:
        path: "{{ config_dir }}"
        state: directory
        mode: "0755"

    - name: Symlink neovim configuration to ~/.config/nvim
      ansible.builtin.file:
        src: "{{ repository_dir }}/nvim"
        dest: "{{ config_dir }}/nvim"
        state: link
        force: true

    - name: Symlink bash configuration to ~/.config/.bashrc
      ansible.builtin.file:
        src: "{{ repository_dir }}/bash/bashrc"
        dest: "{{ ansible_env.HOME }}/.bashrc"
        state: link
        force: true

    - name: Symlink bash configuration to ~/.config/.bashrc.d
      ansible.builtin.file:
        src: "{{ repository_dir }}/bash/bashrc.d"
        dest: "{{ ansible_env.HOME }}/.bashrc.d"
        state: link
        force: true

    - name: Symlink bat configuration to ~/.config/bat
      ansible.builtin.file:
        src: "{{ repository_dir }}/bat"
        dest: "{{ config_dir }}/bat"
        state: link
        force: true

    - name: Symlink bat configuration to ~/.config/ghostty
      ansible.builtin.file:
        src: "{{ repository_dir }}/ghostty"
        dest: "{{ config_dir }}/ghostty"
        state: link
        force: true

    - name: Run bat cache
      ansible.builtin.command:
        cmd: bat cache --build
