# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook

- name: System setup for Ubuntu (system-level tasks)
  hosts: localhost
  become: true
  tasks:
    - name: Ensure target system is Debian or Ubuntu
      ansible.builtin.assert:
        that:
          - ansible_distribution in ['Debian', 'Ubuntu']
        fail_msg: "This playbook requires Debian or Ubuntu on the target server"

    - name: Add git-core PPA repository for the latest git
      ansible.builtin.apt_repository:
        repo: ppa:git-core/ppa
        state: present

    - name: Upgrade the current system
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Install dependencies for neovim configuration
      ansible.builtin.apt:
        state: latest
        pkg:
          - git
          - unzip
          - make
          - gcc
          - python3-venv
          - fzf
          - fd-find
          - ripgrep
          - wl-clipboard
          - dbus-bin

    - name: Install dependencies for neovim configuration
      ansible.builtin.apt:
        state: latest
        pkg:
          - jq
          - yq

    - name: Install bat
      ansible.builtin.import_tasks: tasks/bat.yaml
      tags: bat

    - name: Install eza
      ansible.builtin.import_tasks: tasks/eza.yaml
      tags: eza

    - name: Install fnm and node LTS
      ansible.builtin.import_tasks: tasks/fnm.yaml
      tags: fnm

    - name: Install neovim
      ansible.builtin.import_tasks: tasks/nvim.yaml
      tags: neovim

    - name: Add binary from /opt to PATH
      ansible.builtin.copy:
        dest: /etc/profile.d/extra-binaries-opt.sh
        mode: "0644"
        content: |
          export PATH="/opt/bat:$PATH"
          export PATH="/opt/eza:$PATH"
          export PATH="/opt/nvim-linux-x86_64/bin:$PATH"

- name: User-specific configuration for fnm and neovim
  hosts: localhost
  tasks:
    - name: Ensure .config directory exists in the user's home
      file:
        path: "{{ ansible_env.HOME }}/.config"
        state: directory
        mode: "0755"

    - name: Symlink neovim configuration from ~/.dotconfigs/nvim to ~/.config/nvim
      file:
        src: "{{ ansible_env.HOME }}/.dotconfigs/nvim"
        dest: "{{ ansible_env.HOME }}/.config/nvim"
        state: link
        force: yes
