---
- name: Install fnm to /opt/fnm
  ansible.builtin.shell: |
    curl -fsSL https://fnm.vercel.app/install | bash -s -- --install-dir "/opt/fnm" --skip-shell
  args:
    executable: /bin/bash

- name: Change group ownership of /opt/fnm to 'users'
  ansible.builtin.file:
    path: /opt/fnm
    group: users
    recurse: yes

- name: Set group permissions (rwx) for directories under /opt/fnm
  ansible.builtin.shell: find /opt/fnm/ -type d -exec chmod g+rwx {} +
  args:
    executable: /bin/bash

- name: Create FNM initialization profile
  ansible.builtin.copy:
    dest: /etc/profile.d/fnm.sh
    mode: "0644"
    content: |
      # FNM initialization script

      FNM_PATH='/opt/fnm'
      if [ -d "$FNM_PATH" ]; then
          export PATH="$FNM_PATH:$PATH"
          if [ ! -t 0 ]; then
              # if running noninteractive only register the command
              eval "`fnm env --fnm-dir=\"$FNM_PATH\"`"
          else
              eval "`fnm env --fnm-dir=\"$FNM_PATH\" --use-on-cd --version-file-strategy=recursive --resolve-engines`"
              # register completions
              eval "`fnm completions`"
          fi
      fi

- name: Source FNM profile and install Node LTS
  ansible.builtin.shell: |
    source /etc/profile.d/fnm.sh
    fnm install --lts
    fnm use default
  args:
    executable: /bin/bash
