---
- name: Download starship
  get_url:
    url: https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz
    dest: /tmp/starship-x86_64-unknown-linux-gnu.tar.gz
  register: starship_download

- name: Remove existing starship installation
  ansible.builtin.file:
    path: /opt/starship
    state: absent
  when: starship_download.changed # Remove only if the tarball was re-downloaded

- name: Create a new directory for starship
  ansible.builtin.file:
    path: /opt/starship
    state: directory
    mode: "0755"
  when: starship_download.changed # Create only if the tarball was re-downloaded

- name: Extract starship install files
  ansible.builtin.unarchive:
    src: /tmp/starship-x86_64-unknown-linux-gnu.tar.gz
    dest: /opt/starship
    owner: root
    group: root
    remote_src: yes
  when: starship_download.changed # Extract only if the tarball was re-downloaded

- name: Clean up downloaded tarball
  ansible.builtin.file:
    path: /tmp/starship-x86_64-unknown-linux-gnu.tar.gz
    state: absent
