---
- name: Download yazi tarball
  ansible.builtin.get_url:
    url: https://github.com/sxyazi/yazi/releases/latest/download/yazi-x86_64-unknown-linux-gnu.zip
    dest: /tmp/yazi-x86_64-unknown-linux-gnu.zip
    mode: "0644"
  register: download_status

- name: Remove existing yazi installation
  ansible.builtin.file:
    path: /opt/yazi
    state: absent
  when: download_status.changed # Remove only if the tarball was re-downloaded

- name: Create a new directory for yazi
  ansible.builtin.file:
    path: /opt/yazi/
    state: directory
    mode: "0755"
  when: download_status.changed # Create only if the tarball was re-downloaded

- name: Extract yazi files to /tmp
  ansible.builtin.unarchive:
    src: /tmp/yazi-x86_64-unknown-linux-gnu.zip
    dest: /tmp
    remote_src: yes
  when: download_status.changed # Extract only if the tarball was re-downloaded

- name: Install bat files to /opt
  copy:
    src: /tmp/yazi-x86_64-unknown-linux-gnu/
    dest: /opt/yazi
    mode: "0755"
    owner: root
    group: root
    remote_src: yes
  when: download_status.changed # Create only if the tarball was re-downloaded

- name: Clean up downloaded tarball
  ansible.builtin.file:
    path: /tmp/yazi-x86_64-unknown-linux-gnu.zip
    state: absent

- name: Clean up downloaded tarball extract
  ansible.builtin.file:
    path: /tmp/yazi-x86_64-unknown-linux-gnu
    state: absent
