---
- name: Retrieve latest release information from github
  ansible.builtin.uri:
    url: https://api.github.com/repos/sharkdp/fd/releases/latest
    method: GET
    return_content: true
  register: fd_github_response

- name: Select download url from json response
  ansible.builtin.set_fact:
    fd_download_url: "{{ 0 | extract(fd_github_response.json | community.general.json_query(url_query)) }}"
  vars:
    url_query: assets[?ends_with(browser_download_url,'x86_64-unknown-linux-gnu.tar.gz')].browser_download_url

- name: Get directory name for content in tarball
  ansible.builtin.set_fact:
    fd_directory: "{{ fd_download_url | regex_search('fd-.+-x86_64-unknown-linux-gnu') }}"

- name: Download fd tarball
  ansible.builtin.get_url:
    url: "{{ fd_download_url }}"
    dest: "/tmp/{{ fd_directory }}.tar.gz"
    mode: "0644"
  register: download_status

- name: Remove existing fd installation
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/opt/fd"
    state: absent
  when: download_status.changed # Remove only if the tarball was re-downloaded

- name: Extract fd files to /tmp
  ansible.builtin.unarchive:
    src: "/tmp/{{ fd_directory }}.tar.gz"
    dest: /tmp
    remote_src: yes
  when: download_status.changed # Extract only if the tarball was re-downloaded

- name: Install fd files to /opt
  copy:
    src: "/tmp/{{ fd_directory }}/"
    dest: "{{ ansible_env.HOME }}/.local/opt/fd/"
    remote_src: yes
  when: download_status.changed # Create only if the tarball was re-downloaded

- name: Create symlink to binary
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.local/opt/fd/fd"
    dest: "{{ ansible_env.HOME }}/.local/bin/fd"
    state: link
    force: yes

- name: Clean up downloaded tarball
  ansible.builtin.file:
    path: "/tmp/{{ fd_directory }}.tar.gz"
    state: absent

- name: Clean up downloaded tarball extract
  ansible.builtin.file:
    path: "/tmp/{{ fd_directory }}"
    state: absent
