---
- name: Download neovim tarball
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
    dest: /tmp/nvim-linux-x86_64.tar.gz
    mode: "0644"
  register: download_status

- name: Remove existing nvim installation
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/opt/nvim"
    state: absent
  when: download_status.changed # Remove only if the tarball was re-downloaded

- name: Extract neovim to /tmp
  ansible.builtin.unarchive:
    src: /tmp/nvim-linux-x86_64.tar.gz
    dest: /tmp
    remote_src: yes
  when: download_status.changed # Extract only if the tarball was re-downloaded

- name: Install neovim files to /opt
  copy:
    src: "/tmp/nvim-linux-x86_64/"
    dest: "{{ ansible_env.HOME }}/.local/opt/nvim/"
    remote_src: yes
  when: download_status.changed # Create only if the tarball was re-downloaded

- name: Create symlink to binary
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.local/opt/nvim/bin/nvim"
    dest: "{{ ansible_env.HOME }}/.local/bin/nvim"
    state: link
    force: yes

- name: Clean up downloaded tarball
  ansible.builtin.file:
    path: /tmp/nvim-linux-x86_64.tar.gz
    state: absent

- name: Clean up downloaded tarball extract
  ansible.builtin.file:
    path: /tmp/nvim-linux-x86_64
    state: absent
