---
- name: Download starship
  get_url:
    url: https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz
    dest: /tmp/starship-x86_64-unknown-linux-gnu.tar.gz
  register: starship_download

- name: Remove existing starship installation
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/opt/starship"
    state: absent
  when: starship_download.changed # Remove only if the tarball was re-downloaded

- name: Create starship directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/opt/starship"
    state: directory
  when: starship_download.changed # Create only if the tarball was re-downloaded

- name: Extract starship install files
  ansible.builtin.unarchive:
    src: /tmp/starship-x86_64-unknown-linux-gnu.tar.gz
    dest: "{{ ansible_env.HOME }}/.local/opt/starship/"
    remote_src: yes
  when: starship_download.changed # Extract only if the tarball was re-downloaded

- name: Create symlink to binary
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.local/opt/starship/starship"
    dest: "{{ ansible_env.HOME }}/.local/bin/starship"
    state: link
    force: yes

- name: Clean up downloaded tarball
  ansible.builtin.file:
    path: /tmp/starship-x86_64-unknown-linux-gnu.tar.gz
    state: absent
