---
- name: Download yazi tarball
  ansible.builtin.get_url:
    url: https://github.com/sxyazi/yazi/releases/latest/download/yazi-x86_64-unknown-linux-gnu.zip
    dest: /tmp/yazi-x86_64-unknown-linux-gnu.zip
    mode: "0644"
  register: download_status

- name: Remove existing yazi installation
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/opt/yazi/"
    state: absent
  when: download_status.changed # Remove only if the tarball was re-downloaded

- name: Extract yazi files to /tmp
  ansible.builtin.unarchive:
    src: /tmp/yazi-x86_64-unknown-linux-gnu.zip
    dest: /tmp
    remote_src: yes
  when: download_status.changed # Extract only if the tarball was re-downloaded

- name: Install yazi files to /opt
  copy:
    src: /tmp/yazi-x86_64-unknown-linux-gnu/
    dest: "{{ ansible_env.HOME }}/.local/opt/yazi/"
    mode: "0755"
    remote_src: yes
  when: download_status.changed # Create only if the tarball was re-downloaded

- name: Create symlink to binary
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.local/opt/yazi/yazi"
    dest: "{{ ansible_env.HOME }}/.local/bin/yazi"
    state: link
    force: yes

- name: Create symlink to binary
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.local/opt/yazi/ya"
    dest: "{{ ansible_env.HOME }}/.local/bin/ya"
    state: link
    force: yes

- name: Clean up downloaded tarball
  ansible.builtin.file:
    path: /tmp/yazi-x86_64-unknown-linux-gnu.zip
    state: absent

- name: Clean up downloaded tarball extract
  ansible.builtin.file:
    path: /tmp/yazi-x86_64-unknown-linux-gnu
    state: absent
