# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Source secrets (API keys, tokens, etc.)
if [ -f ~/.secrets ]; then
	. ~/.secrets
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
	PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Default editor for commands
if which nvim &>/dev/null; then
	export EDITOR="nvim"
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*.sh; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done

	unset rc
fi
export LD_LIBRARY_PATH=/home/eddyca/.local/opt/oracle/instantclient_23_26:$LD_LIBRARY_PATH
